service: hrms
frameworkVersion: "2"

custom:
  serverless-offline:
    httpPort: 5000
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.secrets.NODE_ENV}
  region: ap-south-1
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}

functions:
  hello:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline
